- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-pytest
  rev: v4.1.1
  hooks:
    - id: pytest
      args: ['--', '-k', 'test_', 'main.py']
